version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                - HOST_USER_ID=${HOST_USER_ID}
                - HOST_GROUP_ID=${HOST_GROUP_ID}
        ports:
            - "${APP_PORT}:80"
        user: "${HOST_USER_ID}:${HOST_GROUP_ID}"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres:15
        ports:
            - ${POSTGRES_PORT}:${DB_PORT}
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - .env
        command: postgres -c max_connections=200
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "${NGINX_PORT}:80"
            - "${NGINX_SSL_PORT}:443"
        volumes:
            - .:/var/www/html
        depends_on:
            - app
        restart: unless-stopped
volumes:
    postgres:
        driver: local
